# Generated by Django 5.1.3 on 2024-11-12 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_visitas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='me_gusta', to=settings.AUTH_USER_MODEL),
        ),
    ]
